repos:
  - repo: local
    hooks:
      - id: license-header-check
        name: Run license-check script
        entry: ./ci/scripts/license_check.py
        language: python
        types_or: [python, rust]
        pass_filenames: true
        always_run: false
  - repo: local
    hooks:
      - id: check-copied-files
        name: Run check-copied-files script
        entry: ./ci/scripts/check_copied_files.py
        language: python
        pass_filenames: true
        always_run: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
        exclude: "mkdocs.yml"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff
        # 1. Attempt to automatically fix any lint issues.
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22             # Use the latest stable version
    hooks:
      - id: mdformat
        additional_dependencies:
        - mdformat-tables
        - mdformat-gfm
        - mdformat-black
        - mdformat-frontmatter
        - black==25.12.0
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        name: detect-secrets (everything but notebooks)
        args: ['--baseline', '.secrets.baseline', '--exclude-files', '(.*\.ipynb|.*\.baseline)$', ]
        exclude: package.lock.json
      - id: detect-secrets
        name: detect-secrets (notebooks only)
        args: ['--baseline', '.secrets-nb.baseline', '--exclude-files', '^.(?!.*\.ipynb)', '--exclude-lines', '"(hash|id|image/\w+)":.*|<.*at 0x[0-9a-f]+>|object at 0x[0-9a-f]+', ]
