# @package _global_
defaults:
  - /base
  - _self_

resource_shape: gpu.2xh100-sxm
node_group: yo-bom-lepton-001
recipe_subdir: esm2_native_te
branch: jwilber/add-esm2-configs

wandb_init_args:
  project: "lepton_recipe_convergence_${sanitize:${branch}}"
  group: "${recipe_subdir}_${resource_shape}"
  job_type: "training"

train_cmd: train_fsdp2 # mfsdp
num_train_steps: 100

products:
  - config: L0_sanity
#     resource_shape: gpu.2xh200
#   # - config: L1_3B
#   #   resource_shape: gpu.2xh200
#   # - config: L1_15B_perf_test

train_script: |
  torchrun ${train_cmd}.py \
    --config-name ${config}.yaml \
    num_train_steps=${num_train_steps} \
    wandb_init_args.mode=${wandb_init_args.mode} \
    +wandb_init_args.project=${wandb_init_args.project} \
    +wandb_init_args.group=${wandb_init_args.group}
