# @package _global_
defaults:
  - /base
  - _self_

# lepton info
node_group: yo-bom-lepton-001
num_nodes: 1
device_type: gpu
num_devices: 2
gpu_type: h100-sxm
total_gpus: ${multiply:${num_devices},${num_nodes}}
resource_shape: "${device_type}.${num_devices}x${gpu_type}"

# recipe identifiers
recipe_subdir: esm2_native_te_mfsdp_thd
model_type: esm2

# wandb
wandb_init_args:
  project: "test_convergence__recipes__${sanitize:${branch}}"
  group: "${model_type}__${task_cmd}__${total_gpus}__${sanitize:${gpu_type}}"
  job_type: "${recipe_subdir}"
  name: null

# train specific commands
task_cmd: train
num_train_steps: 100

# configs to run
products:
  # - config: L1_15B_perf_test
  #   micro_batch_size: 4
  # - config: L1_3B_ddp
  #   micro_batch_size: 32
  - config: L1_650M
    wandb_name: "${config}__${now:%Y%m%d-%H%M%S}__${gitsha:}"
    micro_batch_size: 16

# training script to run
run_script: |
  torchrun ${task_cmd}.py \
    --config-name ${config}.yaml \
    num_train_steps=${num_train_steps} \
    micro_batch_size=${micro_batch_size} \
    +wandb_init_args.mode=${wandb_init_args.mode} \
    wandb_init_args.project=${wandb_init_args.project} \
    +wandb_init_args.group=${wandb_init_args.group} \
    +wandb_init_args.job_type=${wandb_init_args.job_type} \
    wandb_init_args.name=${wandb_name}
